---
deployment:
  name: teste-app
  namespace: default
  image:
    repository: "nginx"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  replicaCount: 2

  resources:
    limits:
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
